Export: you have to specify what you want to export
PASTA-ELN/pasta-eln pull request #285
Opened 2024-05-13 14:46 UTC by SteffenBrinckmann

2024-05-14 09:25 UTC, SteffenBrinckmann commented
@jmurugan-fzj This is complete from my side: I do not understand why the test fails. Can you help?

2024-05-14 12:10 UTC, jmurugan-fzj commented
> @jmurugan-fzj This is complete from my side: I do not understand why the test fails. Can you help?

@SteffenBrinckmann This is failing due to the changes you made in exportELN siganture in the previous PR, I shall create a new PR for the tests today, give me sometime (y)

2024-05-14 14:06 UTC, SteffenBrinckmann commented
@jmurugan-fzj  Then we would merge both PRs at the same time? Or would it be better to merge this PR, then you create a new PR, which we merge thereafter?

2024-05-14 14:26 UTC, jmurugan-fzj requested changes

2024-05-14 14:26 UTC, jmurugan-fzj commented on pasta_eln/gui.py
> +    # self.setWindowState(Qt.WindowMaximized)  # type: ignore
Can we remove this comments if not needed?

2024-05-14 14:26 UTC, jmurugan-fzj commented on pasta_eln/inputOutput.py
> +    sys.path.append('/home/steffen/FZJ/DataScience/Repositories/TheELNConsortium/TheELNFileFormat/tests/')
What's this strange path in production code?

2024-05-14 14:26 UTC, jmurugan-fzj commented on pasta_eln/inputOutput.py
> +    from test_00_pypi_rocrate         import testFile as roCrateTest
why do we have test methods/modules imported here?

2024-05-14 14:44 UTC, jmurugan-fzj commented
> @jmurugan-fzj Then we would merge both PRs at the same time? Or would it be better to merge this PR, then you create a new PR, which we merge thereafter?

@SteffenBrinckmann Could you please review my PR quickly, this will fix the pytest errors and you can work on the pylint errors as part of this PR or separately...!

2024-05-14 15:04 UTC, SteffenBrinckmann commented
@jmurugan-fzj now it should be good

2024-05-14 15:06 UTC, jmurugan-fzj commented
> @jmurugan-fzj now it should be good

@SteffenBrinckmann Could you address the comments also quickly?

2024-05-15 07:19 UTC, SteffenBrinckmann commented
@jmurugan-fzj Sorry, I had overlooked those. Thanks, they made much sense.

2024-05-15 08:01 UTC, jmurugan-fzj approved these changes

2024-05-15 11:25 UTC, merged